/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/glb/parrot.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import ParrGlb from 'assets/glb/parrot.glb'

const Model = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(ParrGlb)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="RootNode0" scale={0.01} position={[0, 0, 0]}>
          <group name="geo1">
            <skinnedMesh name="pirate_parrot2" geometry={nodes.pirate_parrot2.geometry} material={nodes.pirate_parrot2.material} skeleton={nodes.pirate_parrot2.skeleton} />
          </group>
          <group name="skeletal3">
            <primitive object={nodes.Root_Jnt4} />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Model;

useGLTF.preload(ParrGlb)
